CI: Prepare for building in CLANG64 environments of MSYS2.
This change prepares the rules for building with the CLANG64 environment.
That environment is based on a LLVM toolchain (i.e., `clang`, `clang++`,
and `flang` as the compilers, `lld` as the linker, `libomp` as the OpenMP
implementation, ...).

Trying to build in that environment currently fails with the following
compiler error:
```
error: loc("D:/a/elmerfem/elmerfem/fhutiter/src/huti_bicgstab.F90":861:5): C:/M/B/src/flang-18.1.8.src/lib/Optimizer/CodeGen/TargetRewrite.cpp:495: not yet implemented: passing argument or result on the stack in indirect calls
LLVM ERROR: aborting
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: D:/a/_temp/msys64/clang64/bin/flang -fc1 -triple x86_64-w64-windows-gnu -emit-obj -D CONTIG= -D HAVE_EXECUTECOMMANDLINE -D MINGW32 -D USE_ARPACK -D USE_ISO_C_BINDINGS -D WIN32 -D fhuti_EXPORTS -I D:/a/elmerfem/elmerfem/build -I D:/a/elmerfem/elmerfem/build/fhutiter/src -fopenmp -mrelocation-model pic -pic-level 2 -target-cpu x86-64 -fversion-loops-for-stride -module-dir ../../fmodules -mframe-pointer=none -O3 -o CMakeFiles/fhuti.dir/huti_bicgstab.F90.obj -x f95-cpp-input D:/a/elmerfem/elmerfem/fhutiter/src/huti_bicgstab.F90
make[2]: *** [fhutiter/src/CMakeFiles/fhuti.dir/build.make:101: fhutiter/src/CMakeFiles/fhuti.dir/huti_bicgstab.F90.obj] Error 1
```

diff --git a/.github/workflows/build-windows-mingw.yaml b/.github/workflows/build-windows-mingw.yaml
--- a/.github/workflows/build-windows-mingw.yaml
+++ b/.github/workflows/build-windows-mingw.yaml
@@ -9,47 +9,83 @@ concurrency: ci-windows-mingw-${{ github.ref }}
 jobs:
 
   windows-mingw:
+
     runs-on: windows-latest
+
     defaults:
       run:
         shell: msys2 {0}
-    
+
+    strategy:
+      # Allow other runners in the matrix to continue if some fail
+      fail-fast: false
+
+      matrix:
+        # msystem: [MINGW64, CLANG64]
+        msystem: [MINGW64]
+
     steps:
-      - uses: actions/checkout@v4
-      
-      - uses: msys2/setup-msys2@v2
+      - name: checkout repository
+        uses: actions/checkout@v4
+
+      - name: install dependencies
+        uses: msys2/setup-msys2@v2
         with:
-          msystem: MINGW64
+          msystem: ${{ matrix.msystem }}
           update: true
           install: >-
-            git
-            mingw-w64-x86_64-gcc
-            mingw-w64-x86_64-gcc-fortran
-            mingw-w64-x86_64-cmake
-            mingw-w64-x86_64-openblas
-            mingw-w64-x86_64-parmetis
             base-devel
-      
-      - name: Configure
+            git
+          pacboy: >-
+            cc:p
+            fc:p
+            cmake:p
+            openblas:p
+            parmetis:p
+
+      - name: configure
         run: |
-          mkdir build
-          cd build
-          cmake .. -G "MSYS Makefiles" \
+          mkdir ${GITHUB_WORKSPACE}/build
+          cd ${GITHUB_WORKSPACE}/build
+          cmake \
+            -G "MSYS Makefiles" \
             -DCMAKE_BUILD_TYPE="Release" \
+            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/usr" \
+            -DCPACK_BUNDLE_EXTRA_WINDOWS_DLLS=OFF \
             -DBLA_VENDOR="OpenBLAS" \
             -DWITH_OpenMP=ON \
             -DWITH_LUA=ON \
             -DWITH_Zoltan=OFF \
             -DWITH_Mumps=OFF \
             -DCREATE_PKGCONFIG_FILE=ON \
-            -DWITH_MPI=OFF
-      
-      - name: Build
+            -DWITH_MPI=OFF \
+            ..
+
+      - name: build
         run: |
-          cd build
-          cmake --build .
-      
-      - name: Test
+          cd ${GITHUB_WORKSPACE}/build
+          cmake --build . -j$(nproc)
+
+      - name: install
         run: |
-          cd build
-          ctest -L quick
+          cd ${GITHUB_WORKSPACE}/build
+          cmake --install .
+
+      - name: check
+        id: run-ctest
+        timeout-minutes: 150
+        run: |
+          cd ${GITHUB_WORKSPACE}/build
+          ctest -L quick -j$(nproc)
+
+      - name: re-run tests
+        if: always() && (steps.run-ctest.outcome == 'failure')
+        timeout-minutes: 60
+        run: |
+          cd ${GITHUB_WORKSPACE}/build
+          echo "::group::Re-run failing tests"
+          ctest --rerun-failed --output-on-failure || true
+          echo "::endgroup::"
+          echo "::group::Log from these tests"
+          [ ! -f Testing/Temporary/LastTest.log ] || cat Testing/Temporary/LastTest.log
+          echo "::endgroup::"
