Show more output for failing tests in full CI runs on Ubuntu.
Also remove potential "_np*" suffix from test name to get the name of the
folder containing the test data.

diff --git a/.github/workflows/ubuntu-gcc-full.yaml b/.github/workflows/ubuntu-gcc-full.yaml
--- a/.github/workflows/ubuntu-gcc-full.yaml
+++ b/.github/workflows/ubuntu-gcc-full.yaml
@@ -87,7 +87,7 @@ jobs:
           CTEST_OUTPUT_ON_FAILURE: 1
         run: |
           cd ${GITHUB_WORKSPACE}/build
-          ctest . -j$(nproc)
+          set -o pipefail && ctest . -j$(nproc) | tee ./ctest_output.log
 
       - name: re-run tests
         if: always() && (steps.run-ctest.outcome == 'failure')
@@ -96,6 +96,33 @@ jobs:
           CTEST_OUTPUT_ON_FAILURE: 1
         run: |
           cd ${GITHUB_WORKSPACE}/build
+          # read names of failed tests from log and strip potential "_np*" suffix
+          failed_tests=($(sed -n 's/^.*#[0-9]*\:\s*\(\S*\).*Failed.*/\1/p' ./ctest_output.log | sed -e 's/_np[0-9]*$//g'))
+          # remove duplicate test names
+          declare -A unique_failed_tests
+          for test in "${failed_tests[@]}"; do
+            unique_failed_tests["${test}"]="${test}";
+          done
+          for test in "${unique_failed_tests[@]}"; do
+            # check if test is from fem or ElmerIce
+            if [ -d fem/tests/${test} ]; then
+              test_root=fem/tests
+            else
+              test_root=elmerice/Tests
+            fi
+            echo "::group::Content of ${test_root}/${test}"
+            echo ---- Files ----
+            ls -Rl ${test_root}/${test}
+            if [ -f ${test_root}/${test}/test-stderr*.log ]; then
+              echo ---- Content of test-stderr*.log ----
+              cat ${test_root}/${test}/test-stderr*.log
+            fi
+            if [ -f ${test_root}/${test}/test-stdout*.log ]; then
+              echo ---- Content of test-stdout*.log ----
+              cat ${test_root}/${test}/test-stdout*.log
+            fi
+            echo "::endgroup::"
+          done
           echo "::group::Re-run failing tests"
           ctest --rerun-failed --output-on-failure || true
           echo "::endgroup::"
